change awake_start to support tessie wake

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -1,6 +1,6 @@
 #!/bin/bash -eu
 
-if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) ]]
+if [[ ( ( ! -x /root/bin/tesla_api.py) || ( ! -s /mutable/cache.json ) ) && ( -z "${TESLAFI_API_TOKEN:+x}" ) && ( -z "${TESSIE_API_TOKEN:+x}" ) ]]
 then
   log "Not keeping car awake."
   exit
@@ -26,6 +26,19 @@ function ping {
     then
       curl -s -H "Authorization: Bearer $TESLAFI_API_TOKEN" "https://www.teslafi.com/feed.php?command=wake_up"
       # No need to contact TeslaFi too often to prevent API lockout (max 3 calls/min).
+      sleep 600
+    fi
+
+    if [[ ( -n "${TESSIE_API_TOKEN:+x}" ) ]]
+    # Use Tessie API to keep car awake.
+    then
+      http_status=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $TESSIE_API_TOKEN" -H "Accept: application/json" "https://api.tessie.com/$TESSIE_VIN/wake")
+      
+      if [ "$http_status" != "200" ]; then
+          # Log an error
+          log "Failed to contact car using Tessie API. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. Retrying in 5mins..."
+      fi
+      
       sleep 600
     fi    
   done
