further error checking

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -29,22 +29,42 @@ function ping {
       sleep 600
     fi
 
-    if [[ ( -n "${TESSIE_API_TOKEN:+x}" ) ]]
-    # Use Tessie API to keep car awake.
+    if [[ -n "${TESSIE_API_TOKEN:+x}" ]]
+    # Use Tessie API to keep car awake
     then
-      http_status=$(curl -s -o /dev/null -w "%{http_code}" \
-          -H "Authorization: Bearer $TESSIE_API_TOKEN" \
-          -H "Accept: application/json" \
-          -H "User-Agent: github.com/marcone/teslausb" \
-          "https://api.tessie.com/$TESSIE_VIN/wake")
-      
-      if [ "$http_status" != "200" ]; then
-          # Log an error
-          log "Failed to contact car using Tessie API. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection.  Retrying in 3mins..."
-      fi
-      
-      sleep 180
-    fi    
+        http_response=$(curl -s -w "%{http_code}" \
+            -H "Authorization: Bearer $TESSIE_API_TOKEN" \
+            -H "Accept: application/json" \
+            -H "User-Agent: github.com/marcone/teslausb" \
+            "https://api.tessie.com/$TESSIE_VIN/wake")
+        
+        # Extract HTTP status code
+        http_status="${http_response: -3}"
+        
+        # Extract response body (excluding status code)
+        response_body="${http_response:0:${#http_response}-3}"
+        
+        # Check if HTTP status code is not 200 (OK)
+        if [ "$http_status" != "200" ]; then
+            # Log an error
+            log "Failed to contact car using Tessie API. Check your TESSIE_API_TOKEN and TESSIE_VIN are set correctly. If they are, your car may not have a good connection. Retrying in 5 minutes..."
+        else
+            # Check if the response is in JSON format
+            if ! jq -e . >/dev/null 2>&1 <<<"$response_body"; then
+                log "Error: Response is not in JSON format. Response data: $response_body"
+            else
+                # Parse JSON and check if "result" is true
+                result=$(jq -r '.result' <<<"$response_body")
+                if [[ "$result" != "true" ]]; then
+                    log "Error: Result is not true. Response data: $response_body"
+                else
+                    log "Success! Car is awake."
+                fi
+            fi
+        fi
+        
+        sleep 300
+    fi  
   done
 }
 
